In [8]:
import pandas as pd
essay_point = pd.read_csv('/home/daegon/Multi-Scale-BERT-AES/datatouch/korproject/kor_essayset2_point.csv',index_col = 0)
essay_point

논리성  참신성  설득력
id                 
1       4    4    3
2       1    2    1
3       3    3    2
4       4    3    3
5       3    3    3
...   ...  ...  ...
1796    2    2    2
1797    3    2    3
1798    1    0    1
1799    3    2    3
1800    4    3    4

[1800 rows x 3 columns]

In [7]:
essay_point.논리성.unique(), essay_point.참신성.unique(), essay_point.설득력.unique()

(array([4, 1, 3, 2, 0, 5]),
 array([4, 2, 3, 1, 5, 0]),
 array([3, 1, 2, 4, 5, 0]))

In [10]:
essay_point.논리성.to_list()

[4,
 1,
 3,
 4,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 3,
 4,
 4,
 0,
 3,
 4,
 4,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 3,
 4,
 2,
 2,
 3,
 2,
 2,
 3,
 4,
 3,
 2,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 2,
 3,
 3,
 3,
 2,
 1,
 4,
 3,
 4,
 3,
 2,
 4,
 5,
 4,
 4,
 3,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 4,
 2,
 1,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 3,
 1,
 1,
 3,
 2,
 3,
 2,
 2,
 3,
 2,
 4,
 2,
 4,
 3,
 2,
 3,
 2,
 3,
 2,
 3,
 4,
 3,
 3,
 2,
 1,
 4,
 3,
 3,
 3,
 2,
 3,
 4,
 4,
 3,
 3,
 5,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 2,
 3,
 3,
 3,
 3,
 3,
 4,
 2,
 1,
 2,
 3,
 4,
 2,
 3,
 4,
 2,
 2,
 3,
 4,
 3,
 2,
 3,
 3,
 3,
 3,
 2,
 2,
 4,
 2,
 3,
 3,
 3,
 3,
 4,
 4,
 2,
 3,
 4,
 2,
 3,
 3,
 4,
 5,
 2,
 3,
 3,
 4,
 2,
 3,
 4,
 5,
 4,
 4,
 3,
 3,
 3,
 4,
 3,
 3,
 2,
 3,
 4,
 3,
 4,
 4,
 3,
 3,
 4,
 3,
 3,
 3,
 3,
 4,
 4,
 3,
 4,
 3,
 3,
 4,
 3,
 4,
 3,
 3,
 2,
 3,
 4,
 4,
 4,
 3,


In [15]:
essays = pd.read_csv('/home/daegon/Multi-Scale-BERT-AES/datatouch/korproject/kor_essayset2.csv', index_col=0)
essays

Kor_essay_3
id                                                     
1     도서, 음악, 잡지와 같은 도서관에서 제거되고 있는 특정 자료들은 도서관에서 제거되...
2     도서관에서 검열하는 것에 대한 당신의 견해를 반영하는 설득력 있는 에세이를 신문에 ...
3     당신은 도서관이 책꽂이에서 특정 자료들을 제거해야 한다고 생각하나요? 사람들은 무엇...
4     세계에는 불쾌감을 주는 것들이 많이 있다. 모든 사람은 무엇이 불쾌하고 무엇이 불쾌...
5     인생에서 당신은 불쾌한 것들을 가지고 있다. 우리의 피부밑에 들어가서 우리를 갉아먹...
...                                                 ...
1796  작가는 어른들이 책의 결말을 원하지 않는 책을 떼어내는 것에 대해 쓰고 있다. 그들...
1797  책, 음악, 영화, 잡지와 같은 재료들이 불쾌하다고 생각될 때 선반에서 치워져야 한...
1798  네, 우리는 책, 음악, 영화, 잡지를 보관해야 합니다. 잡지와 음악은 어떤 사람들...
1799  나는 책, 잡지, 음악, 영화 등은 책이나 잡지를 읽고 싶다면 책꽂이에서 꺼내야 한...
1800  다른 모든 사람 @CAPS1과 다른 사람들은 작은 것들을 불쾌하게 여깁니까?내 의견...

[1800 rows x 1 columns]

In [17]:
essays.rename(columns={'Kor_essay_3':'essay'},inplace=True)
essays

essay
id                                                     
1     도서, 음악, 잡지와 같은 도서관에서 제거되고 있는 특정 자료들은 도서관에서 제거되...
2     도서관에서 검열하는 것에 대한 당신의 견해를 반영하는 설득력 있는 에세이를 신문에 ...
3     당신은 도서관이 책꽂이에서 특정 자료들을 제거해야 한다고 생각하나요? 사람들은 무엇...
4     세계에는 불쾌감을 주는 것들이 많이 있다. 모든 사람은 무엇이 불쾌하고 무엇이 불쾌...
5     인생에서 당신은 불쾌한 것들을 가지고 있다. 우리의 피부밑에 들어가서 우리를 갉아먹...
...                                                 ...
1796  작가는 어른들이 책의 결말을 원하지 않는 책을 떼어내는 것에 대해 쓰고 있다. 그들...
1797  책, 음악, 영화, 잡지와 같은 재료들이 불쾌하다고 생각될 때 선반에서 치워져야 한...
1798  네, 우리는 책, 음악, 영화, 잡지를 보관해야 합니다. 잡지와 음악은 어떤 사람들...
1799  나는 책, 잡지, 음악, 영화 등은 책이나 잡지를 읽고 싶다면 책꽂이에서 꺼내야 한...
1800  다른 모든 사람 @CAPS1과 다른 사람들은 작은 것들을 불쾌하게 여깁니까?내 의견...

[1800 rows x 1 columns]

In [18]:
essays.to_csv('/home/daegon/Multi-Scale-BERT-AES/datatouch/korproject/kor_essayset2.csv')

In [20]:
from sklearn.model_selection import train_test_split

essays = essays.essay.to_list()
points = essay_point.논리성.to_list()
X_train, X_test, Y_train, Y_test = train_test_split(essays, points, test_size=0.33, random_state=321)



In [1]:
Y_train

NameError: name 'Y_train' is not defined

In [5]:
import os.path
if os.path.exists('/home/daegon/Multi-Scale-BERT-AES/models/word_doc_model.bin1'):
    print(1)

In [12]:
import torch
document_batch = torch.randn(1,3,7)
doc_id = 0
# document_batch[doc_id][:1,0]
document_batch[0][:1,0].shape, document_batch[0][:1].shape

(torch.Size([1]), torch.Size([1, 7]))

In [11]:
a =  None
# a = [[1],[2]]
if a and True:
    print(1)

In [9]:
test = [1,2],[3,4]
def a(*test):
    print(test)
a(*test)

([1, 2], [3, 4])


In [1]:
import numpy as np

lp = np.load('./loss_eval/essay_point/logical.npy')
rp = np.load('./loss_eval/essay_point/reason.npy')
pp = np.load('./loss_eval/essay_point/persuasive.npy')
nop = np.load('./loss_eval/essay_point/novelty.npy')
lp.mean(), rp.mean(), pp.mean(), nop.mean()
# 논리성 : 55.65 / 근거의 풍부함 : 53.14 / 설득력 : 45.42 / 참신성 : 48.70

(55.64982406397673, 53.13751145038168, 45.417134860050886, 48.70464994547437)

In [5]:
rp

array([], dtype=float64)